version: '3'
services:

  auth-db:
    image: "postgres:9.6.1"
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "auth"
    restart: always
  vocabulary-db:
    image: "postgres:9.6.1"
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "vocabulary"
    restart: always
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./rabbitmq.env
